In [67]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [68]:
df = pd.read_csv('spam.csv')

In [69]:
df.head(10)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
5,spam,FreeMsg Hey there darling it's been 3 week's n...,NaN,NaN,NaN
6,ham,Even my brother is not like to speak with me. ...,NaN,NaN,NaN
7,ham,As per your request 'Melle Melle (Oru Minnamin...,NaN,NaN,NaN
8,spam,WINNER!! As a valued network customer you have...,NaN,NaN,NaN
9,spam,Had your mobile 11 months or more? U R entitle...,NaN,NaN,NaN

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [71]:
df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace=True)

In [72]:
# rename columns to meaningful names
df.rename(columns={'v1': 'Class', 'v2': 'Email'}, inplace=True)
df.head(10)

  Class                                              Email
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [73]:
# Remove punctuations from our emails 
df["Email"] = df['Email'].str.replace('[^\w\s]','')
df

     Class                                              Email
0      ham  Go until jurong point crazy Available only in ...
1      ham                            Ok lar Joking wif u oni
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham        U dun say so early hor U c already then say
4      ham  Nah I dont think he goes to usf he lives aroun...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham                Will _ b going to esplanade fr home
5569   ham  Pity  was in mood for that Soany other suggest...
5570   ham  The guy did some bitching but I acted like id ...
5571   ham                          Rofl Its true to its name

[5572 rows x 2 columns]

In [74]:
# Lower case all the emails
df.Email = df.Email.str.lower()
df.head()

  Class                                              Email
0   ham  go until jurong point crazy available only in ...
1   ham                            ok lar joking wif u oni
2  spam  free entry in 2 a wkly comp to win fa cup fina...
3   ham        u dun say so early hor u c already then say
4   ham  nah i dont think he goes to usf he lives aroun...

In [75]:
# Check duplication
duplicateRows = df[df.duplicated()] 
duplicateRows

     Class                                              Email
102    ham  as per your request melle melle oru minnaminun...
153    ham  as per your request melle melle oru minnaminun...
206    ham  as i entered my cabin my pa said  happy bday b...
222    ham                               sorry ill call later
325    ham                       no callsmessagesmissed calls
...    ...                                                ...
5535   ham  i know you are thinkin malaria but relax child...
5539   ham                           just sleepingand surfing
5547  spam  had your contract mobile 11 mnths latest motor...
5553   ham                          hahahause your brain dear
5558   ham                               sorry ill call later

[431 rows x 2 columns]

In [76]:
# Remove duplication
df.drop_duplicates(keep = False, inplace = True)

In [77]:
df['Count'] = [len(sent.split(" ")) for sent in df['Email']]
df.reset_index(inplace=True)
df.drop('index', axis=1, inplace=True)
df.head()

  Class                                              Email  Count
0   ham  go until jurong point crazy available only in ...     20
1   ham                            ok lar joking wif u oni      6
2   ham        u dun say so early hor u c already then say     11
3   ham  nah i dont think he goes to usf he lives aroun...     13
4  spam  freemsg hey there darling its been 3 weeks now...     32

In [78]:
# getting total number of distinct words in the emails (aka number of classes)
email_tokens = []
for index, row in df.iterrows():
    email_tokens.append(row['Email'].split(' '))

email_tokens = [j for sub in email_tokens for j in sub]

num_of_classes = len(set(email_tokens))
num_of_classes

8908

In [79]:
# Total number of words in spam emails
num_words_spam = df[df['Class'] == 'spam'].Count.sum()
num_words_spam

12762

In [80]:
# Total number of words in non-spam emails
num_words_ham = df[df['Class'] == 'ham'].Count.sum()
num_words_ham

60893

In [81]:
# Probability of spam class without laplacian smoothing
p_spam = len(df[df['Class'] == 'spam']) / len(df)
p_spam

0.11248710010319918

In [82]:
# Probability of ham class without laplacian smoothing
p_ham = len(df[df['Class'] == 'ham']) / len(df)
p_ham

0.8875128998968008

---
#### Split the data to train/test sets

In [83]:
split = int(0.75*len(df))
df_train = df[:split]
df_test = df[split+1:]

In [84]:
df_train

     Class                                              Email  Count
0      ham  go until jurong point crazy available only in ...     20
1      ham                            ok lar joking wif u oni      6
2      ham        u dun say so early hor u c already then say     11
3      ham  nah i dont think he goes to usf he lives aroun...     13
4     spam  freemsg hey there darling its been 3 weeks now...     32
...    ...                                                ...    ...
3628   ham                im good have you registered to vote      7
3629   ham  hmm ok ill stay for like an hour cos my eye is...     14
3630   ham                   dear got bus directly to calicut      6
3631   ham  mm umma ask vava also to come tell him can pla...     13
3632   ham  well the general price is  ltgt oz let me know...     15

[3633 rows x 3 columns]

In [85]:
df_test

     Class                                              Email  Count
3634   ham                   ltgt  w jetton ave if you forgot      8
3635   ham                              ok im coming home now      5
3636   ham         can not use foreign stamps in this country      8
3637   ham  sorry its a lot of friendofafriend stuff im ju...     21
3638  spam  cmon babe make me horny turn me on txt me your...     30
...    ...                                                ...    ...
4840  spam  this is the 2nd time we have tried 2 contact u...     30
4841   ham                will _ b going to esplanade fr home      8
4842   ham  pity  was in mood for that soany other suggest...     10
4843   ham  the guy did some bitching but i acted like id ...     26
4844   ham                          rofl its true to its name      6

[1211 rows x 3 columns]

---
#### Training

In [86]:
# Calculate liklehood probability
def likelihood(df, token, spam_ham):
    if spam_ham == 1:
        num_words = num_words_spam
        token_count = sum([sent.split(" ").count(token) for sent in df[df['Class'] == 'spam']['Email']])        
    else:
        num_words = num_words_ham
        token_count = sum([sent.split(" ").count(token) for sent in df[df['Class'] == 'ham']['Email']])
        
    return token_count / num_words

In [96]:
# Training Approach: Calculating likehood of every distinct word in all emails in the training dataset

likelihood_spam = {}
likelihood_ham = {}

train_email_tokens = []
for index, row in df_train.iterrows():
    train_email_tokens.append(row['Email'].split(' '))
    
train_email_tokens = [j for sub in train_email_tokens for j in sub]

tokens = set(train_email_tokens)
for word in tokens:
    likelihood_ham[word] = likelihood(df_train, word, 0)
    likelihood_spam[word] = likelihood(df_train, word, 1)

----
#### Testing

In [118]:
# Calculate product of liklehoods of an email
def total_liklehood(email, spam_ham):
    total = 1
    
    if spam_ham == 0:
        words = email.split(" ")
        for word in words:
            if word in likelihood_ham:
                total *= likelihood_ham['word']
    elif spam_ham == 1:
        words = email.split(" ")
        for word in words:
            if word in likelihood_spam:
                total *= likelihood_spam['word']


    return total

In [119]:
# Calculate the probability that an email is spam
def naive_bayes_spam(email):
    email = email.lower()
    p_email_given_spam = total_liklehood(email, 1)
#     print(p_email_given_spam)
    p_email = total_liklehood(email, 1) * p_spam + total_liklehood(email, 0) * p_ham
    print(p_email)
    prob_naive_bayes_spam = (p_email_given_spam * p_spam) / (p_email)
    
    return prob_naive_bayes_spam

In [120]:
def spam_ham_classify(email, threshold):
#     print(naive_bayes_spam(email))
    return 'spam' if naive_bayes_spam(email) >= threshold else 'ham'

# Apply naive bayes to the dataset 
# Since this is imbalanced classification problem, 0.5 threshhold will be a mistake, 0.7 will be good
df_test['Classification'] = df_test['Email'].apply(lambda x: spam_ham_classify(x, 0.7))
df_test.head(10)

3.975821558248423e-23
5.3549356554603165e-17
3.42685144564196e-26
5.762110975474395e-63
2.362790889124965e-81
1.6302867703825892e-41
6.204271457788388e-109
8.998285816015186e-54
3.42685144564196e-26
6.685096388091307e-60
5.3549356554603165e-17
3.975821558248423e-23
8.998285816015186e-54
1.4051993787285787e-44
1.8914290714091943e-38
5.3549356554603165e-17
2.5459049929848763e-32
5.3549356554603165e-17
7.755927282256581e-57
4.6130626872419715e-20
5.3549356554603165e-17
2.1944016341686676e-35
2.1944016341686676e-35
2.5459049929848763e-32
7.755927282256581e-57
1.8914290714091943e-38
4.6130626872419715e-20
2.9537135607967343e-29
5.762110975474395e-63
4.966558590363448e-66
5.3549356554603165e-17
6.235109128196901e-14
1.6302867703825892e-41
5.3549356554603165e-17
6.685096388091307e-60
6.685096388091307e-60
1.5130285471425918e-90
5.3549356554603165e-17
2.9537135607967343e-29
1.0439647598550091e-50
1.5130285471425918e-90
3.975821558248423e-23
4.966558590363448e-66
1.2111889332108396e-47
7.404437851135338e-11
3.42685144564196e-26
1.0439647598550091e-50
1.6302867703825892e-41
3.975821558248423e-23
5.3549356554603165e-17
7.198082940390491e-106
6.685096388091307e-60
7.755927282256581e-57
6.235109128196901e-14
4.280845047327843e-69
1.0439647598550091e-50
4.966558590363448e-66
2.9537135607967343e-29
5.3549356554603165e-17
1.8914290714091943e-38
3.6898053220973413e-72
4.280845047327843e-69
2.362790889124965e-81
1.6302867703825892e-41
3.42685144564196e-26
5.3549356554603165e-17
3.1803681666722106e-75
6.235109128196901e-14
5.762110975474395e-63
2.5459049929848763e-32
4.6130626872419715e-20
3.975821558248423e-23
3.975821558248423e-23
6.235109128196901e-14
2.362790889124965e-81
2.362790889124965e-81
6.235109128196901e-14
6.685096388091307e-60
2.5459049929848763e-32
5.3549356554603165e-17
2.362790889124965e-81
9.688776924801092e-100
1.0439647598550091e-50
4.6130626872419715e-20
3.1781155909386127e-170
5.3549356554603165e-17
1.0
1.8914290714091943e-38
2.5459049929848763e-32
1.8914290714091943e-38
1.6302867703825892e-41
1.6302867703825892e-41
1.0439647598550091e-50
7.755927282256581e-57
7.404437851135338e-11
2.1944016341686676e-35
3.42685144564196e-26
2.036569486003339e-84
2.9537135607967343e-29
1.8914290714091943e-38
1.2111889332108396e-47
1.1232781289784466e-191
8.998285816015186e-54
1.2111889332108396e-47
6.235109128196901e-14
4.966558590363448e-66
8.351084953205769e-103
5.3549356554603165e-17
4.6130626872419715e-20
2.362790889124965e-81
1.2111889332108396e-47
1.2111889332108396e-47
5.3549356554603165e-17
3.42685144564196e-26
7.404437851135338e-11
3.975821558248423e-23
3.42685144564196e-26
1.8914290714091943e-38
5.3549356554603165e-17
3.975821558248423e-23
3.42685144564196e-26
1.2111889332108396e-47
1.2111889332108396e-47
1.4051993787285787e-44
3.42685144564196e-26
4.6130626872419715e-20
3.975821558248423e-23
5.3549356554603165e-17
2.741267029728437e-78
8.351084953205769e-103
4.6130626872419715e-20
7.404437851135338e-11
3.42685144564196e-26
2.362790889124965e-81
3.42685144564196e-26
2.1944016341686676e-35
4.6130626872419715e-20
2.741267029728437e-78
5.762110975474395e-63
2.9537135607967343e-29
3.1803681666722106e-75
4.280845047327843e-69
3.975821558248423e-23
4.966558590363448e-66
6.685096388091307e-60
2.5459049929848763e-32
3.1803681666722106e-75
3.42685144564196e-26
2.5459049929848763e-32
2.5459049929848763e-32
1.8914290714091943e-38
3.1803681666722106e-75
9.888866940702522e-08
2.741267029728437e-78
3.1803681666722106e-75
1.6302867703825892e-41
6.685096388091307e-60
4.280845047327843e-69
4.6130626872419715e-20
2.9537135607967343e-29
3.42685144564196e-26
6.685096388091307e-60
7.404437851135338e-11
2.362790889124965e-81
1.8914290714091943e-38
1.124074282857378e-96
1.755388210784887e-87
2.741267029728437e-78
5.3549356554603165e-17
4.6130626872419715e-20
4.6130626872419715e-20
4.6130626872419715e-20
2.5459049929848763e-32
1.6302867703825892e-41
1.6302867703825892e-41
1.4051993787285787e-44
5.3549356554603165e-17
1.3032068620020852e-188
2.1944016341686676e-35
4.6130626872419715e-20
2.1944016341686676e-35
4.280845047327843e-69
6.235109128196901e-14
3.975821558248423e-23
2.5459049929848763e-32
3.6898053220973413e-72
5.762110975474395e-63
2.9516204847686506e-124
1.6302867703825892e-41
2.5459049929848763e-32
2.5459049929848763e-32
3.975821558248423e-23
7.755927282256581e-57
1.2111889332108396e-47
4.966558590363448e-66
3.97294566906523e-118
4.6130626872419715e-20
3.6898053220973413e-72
2.9537135607967343e-29
3.42685144564196e-26
1.4051993787285787e-44
4.6130626872419715e-20
4.6130626872419715e-20
5.3549356554603165e-17
2.9537135607967343e-29
1.4051993787285787e-44
1.6302867703825892e-41
2.9537135607967343e-29
3.42685144564196e-26
3.6898053220973413e-72
1.4051993787285787e-44
2.1944016341686676e-35
4.966558590363448e-66
3.975821558248423e-23
5.762110975474395e-63
3.975821558248423e-23
2.5459049929848763e-32
2.5459049929848763e-32
3.975821558248423e-23
9.688776924801092e-100
6.235109128196901e-14
4.6130626872419715e-20
4.6130626872419715e-20
1.4051993787285787e-44
4.6130626872419715e-20
2.1912942368779553e-225
2.1944016341686676e-35
3.975821558248423e-23
3.42685144564196e-26
2.1944016341686676e-35
2.5459049929848763e-32
1.2111889332108396e-47
4.280845047327843e-69
1.6291320784711136e-136
1.0432253455596314e-145
1.0439647598550091e-50
6.685096388091307e-60
2.5459049929848763e-32
4.6130626872419715e-20
5.3549356554603165e-17
3.97294566906523e-118
6.685096388091307e-60
5.3549356554603165e-17
3.42685144564196e-26
4.6130626872419715e-20
4.6130626872419715e-20
4.6130626872419715e-20
1.2111889332108396e-47
2.9537135607967343e-29
1.0
3.42685144564196e-26
7.404437851135338e-11
1.2111889332108396e-47
4.966558590363448e-66
6.235109128196901e-14
6.235109128196901e-14
6.235109128196901e-14
1.0439647598550091e-50
2.9537135607967343e-29
2.9537135607967343e-29
2.741267029728437e-78
2.362790889124965e-81
6.235109128196901e-14
1.6302867703825892e-41
1.0439647598550091e-50
4.280845047327843e-69
2.741267029728437e-78
1.4051993787285787e-44
6.235109128196901e-14
7.404437851135338e-11
3.975821558248423e-23
2.1944016341686676e-35
1.8914290714091943e-38
5.3549356554603165e-17
8.351084953205769e-103
5.3549356554603165e-17
7.404437851135338e-11
2.1944016341686676e-35
2.036569486003339e-84
2.9537135607967343e-29
2.5459049929848763e-32
3.42685144564196e-26
2.9537135607967343e-29
1.2111889332108396e-47
6.685096388091307e-60
6.685096388091307e-60
4.966558590363448e-66
4.6130626872419715e-20
3.975821558248423e-23
1.6302867703825892e-41
5.3549356554603165e-17
8.351084953205769e-103
2.036569486003339e-84
2.5459049929848763e-32
2.036569486003339e-84
3.42685144564196e-26
5.762110975474395e-63
3.424416420601593e-121
1.2111889332108396e-47
1.304130545256896e-93
3.975821558248423e-23
4.6130626872419715e-20
3.42685144564196e-26
2.5459049929848763e-32
2.741267029728437e-78
1.6302867703825892e-41
1.755388210784887e-87
2.036569486003339e-84
3.42685144564196e-26
3.975821558248423e-23
8.998285816015186e-54
1.124074282857378e-96
2.362790889124965e-81
1.4051993787285787e-44
2.9516204847686506e-124
3.42685144564196e-26
3.1803681666722106e-75
2.036569486003339e-84
2.5459049929848763e-32
6.235109128196901e-14
1.4051993787285787e-44
4.6130626872419715e-20
5.3549356554603165e-17
1.5130285471425918e-90
4.6130626872419715e-20
1.8914290714091943e-38
3.975821558248423e-23
1.404204110890319e-139
2.1944016341686676e-35
3.6898053220973413e-72
2.741267029728437e-78
9.888866940702522e-08
3.42685144564196e-26
1.4051993787285787e-44
5.3549356554603165e-17
3.975821558248423e-23
6.685096388091307e-60
2.362790889124965e-81
3.42685144564196e-26
6.685096388091307e-60
1.6302867703825892e-41
6.685096388091307e-60
1.4051993787285787e-44
3.6898053220973413e-72
7.755927282256581e-57
5.758029815471075e-158
3.42685144564196e-26
1.4051993787285787e-44
1.6302867703825892e-41
3.6898053220973413e-72
3.975821558248423e-23
4.966558590363448e-66
4.6130626872419715e-20
8.998285816015186e-54
3.42685144564196e-26
3.6898053220973413e-72
4.280845047327843e-69
3.975821558248423e-23
1.0439647598550091e-50
3.42685144564196e-26
7.755927282256581e-57
2.741267029728437e-78
1.2111889332108396e-47
3.42685144564196e-26
5.3549356554603165e-17
3.975821558248423e-23
6.235109128196901e-14
1.8914290714091943e-38
4.6130626872419715e-20
7.755927282256581e-57
1.6302867703825892e-41
6.235109128196901e-14
6.685096388091307e-60
1.2111889332108396e-47
5.3549356554603165e-17
7.404437851135338e-11
4.6130626872419715e-20
1.8914290714091943e-38
3.42685144564196e-26
4.6130626872419715e-20
1.6302867703825892e-41
2.362790889124965e-81
2.9537135607967343e-29
3.975821558248423e-23
7.755927282256581e-57
3.975821558248423e-23
2.9537135607967343e-29
2.1944016341686676e-35
3.975821558248423e-23
4.6130626872419715e-20
1.8914290714091943e-38
3.42685144564196e-26
0.00021355610277377517
1.2111889332108396e-47
5.3549356554603165e-17
4.6130626872419715e-20
1.5130285471425918e-90
1.755388210784887e-87
3.42685144564196e-26
4.966558590363448e-66
2.741267029728437e-78
5.3549356554603165e-17
2.5459049929848763e-32
1.8914290714091943e-38
5.3549356554603165e-17
8.998285816015186e-54
8.998285816015186e-54
1.8914290714091943e-38
4.6130626872419715e-20
5.3549356554603165e-17
6.235109128196901e-14
3.42685144564196e-26
9.888866940702522e-08
5.3549356554603165e-17
2.9537135607967343e-29
1.4051993787285787e-44
2.5459049929848763e-32
1.6302867703825892e-41
4.280845047327843e-69
2.741267029728437e-78
1.5130285471425918e-90
5.3549356554603165e-17
7.404437851135338e-11
2.1944016341686676e-35
3.975821558248423e-23
1.8914290714091943e-38
4.6130626872419715e-20
2.9537135607967343e-29
2.1944016341686676e-35
1.4051993787285787e-44
3.975821558248423e-23
7.404437851135338e-11
3.975821558248423e-23
2.5459049929848763e-32
2.9537135607967343e-29
1.5130285471425918e-90
1.5130285471425918e-90
3.6898053220973413e-72
1.8914290714091943e-38
1.8914290714091943e-38
7.404437851135338e-11
5.3549356554603165e-17
0.00021355610277377517
7.755927282256581e-57
4.6130626872419715e-20
4.6130626872419715e-20
7.755927282256581e-57
4.6130626872419715e-20
2.1944016341686676e-35
1.2111889332108396e-47
1.4051993787285787e-44
6.685096388091307e-60
1.8914290714091943e-38
2.9537135607967343e-29
1.6302867703825892e-41
5.3549356554603165e-17
3.1803681666722106e-75
7.755927282256581e-57
7.755927282256581e-57
1.6302867703825892e-41
2.9537135607967343e-29
1.8914290714091943e-38
7.404437851135338e-11
4.280845047327843e-69
2.9537135607967343e-29
1.0439647598550091e-50
2.741267029728437e-78
3.1803681666722106e-75
7.404437851135338e-11
1.0439647598550091e-50
0.00021355610277377517
3.975821558248423e-23
2.9537135607967343e-29
5.3549356554603165e-17
4.6130626872419715e-20
2.362790889124965e-81
1.0432253455596314e-145
4.6130626872419715e-20
1.0439647598550091e-50
1.8914290714091943e-38
5.3549356554603165e-17
2.9537135607967343e-29
8.998285816015186e-54
4.966558590363448e-66
1.0439647598550091e-50
3.6898053220973413e-72
3.6898053220973413e-72
1.6302867703825892e-41
3.6898053220973413e-72
2.5459049929848763e-32
2.9537135607967343e-29
2.362790889124965e-81
1.304130545256896e-93
2.741267029728437e-78
2.1944016341686676e-35
1.2111889332108396e-47
3.975821558248423e-23
6.235109128196901e-14
3.975821558248423e-23
8.998285816015186e-54
6.235109128196901e-14
1.4051993787285787e-44
3.42685144564196e-26
1.4051993787285787e-44
2.1944016341686676e-35
6.235109128196901e-14
2.1944016341686676e-35
2.1944016341686676e-35
2.9537135607967343e-29
1.4051993787285787e-44
5.762110975474395e-63
1.4051993787285787e-44
1.6302867703825892e-41
8.998285816015186e-54
4.6130626872419715e-20
2.036569486003339e-84
1.6302867703825892e-41
4.280845047327843e-69
2.9537135607967343e-29
3.975821558248423e-23
1.304130545256896e-93
2.5459049929848763e-32
1.6302867703825892e-41
6.235109128196901e-14
4.6130626872419715e-20
4.280845047327843e-69
2.9537135607967343e-29
2.9537135607967343e-29
3.6898053220973413e-72
6.685096388091307e-60
2.9537135607967343e-29
2.9537135607967343e-29
1.124074282857378e-96
1.2103310781847287e-142
3.975821558248423e-23
6.685096388091307e-60
4.6130626872419715e-20
2.1944016341686676e-35
8.998285816015186e-54
4.280845047327843e-69
5.347671684349809e-112
1.5130285471425918e-90
1.2111889332108396e-47
2.5459049929848763e-32
2.1944016341686676e-35
3.42685144564196e-26
1.6302867703825892e-41
8.998285816015186e-54
7.404437851135338e-11
6.235109128196901e-14
4.6130626872419715e-20
3.42685144564196e-26
1.755388210784887e-87
2.362790889124965e-81
2.5459049929848763e-32
4.6130626872419715e-20
1.4051993787285787e-44
1.8914290714091943e-38
2.5459049929848763e-32
8.998285816015186e-54
3.975821558248423e-23
3.42685144564196e-26
4.280845047327843e-69
5.3549356554603165e-17
2.036569486003339e-84
4.6130626872419715e-20
5.3549356554603165e-17
5.762110975474395e-63
1.6302867703825892e-41
8.998285816015186e-54
1.6302867703825892e-41
3.42685144564196e-26
3.975821558248423e-23
2.362790889124965e-81
9.888866940702522e-08
2.1944016341686676e-35
5.3549356554603165e-17
8.998285816015186e-54
2.9537135607967343e-29
2.5459049929848763e-32
5.3549356554603165e-17
4.6130626872419715e-20
6.685096388091307e-60
7.404437851135338e-11
2.9537135607967343e-29
1.4051993787285787e-44
2.362790889124965e-81
1.6302867703825892e-41
7.404437851135338e-11
6.685096388091307e-60
3.42685144564196e-26
3.42685144564196e-26
2.3611173830585345e-176
6.235109128196901e-14
5.762110975474395e-63
1.0439647598550091e-50
3.975821558248423e-23
1.4051993787285787e-44
4.6130626872419715e-20
5.3549356554603165e-17
1.2111889332108396e-47
8.998285816015186e-54
1.0439647598550091e-50
1.4051993787285787e-44
1.0439647598550091e-50
5.3549356554603165e-17
2.9537135607967343e-29
1.4051993787285787e-44
3.975821558248423e-23
6.235109128196901e-14
6.204271457788388e-109
8.351084953205769e-103
1.2111889332108396e-47
2.741267029728437e-78
5.3549356554603165e-17
4.966558590363448e-66
3.42685144564196e-26
3.975821558248423e-23
2.5459049929848763e-32
5.762110975474395e-63
2.1944016341686676e-35
4.966558590363448e-66
4.6130626872419715e-20
3.175864610648427e-265
7.755927282256581e-57
4.6130626872419715e-20
7.404437851135338e-11
3.975821558248423e-23
4.6130626872419715e-20
4.280845047327843e-69
1.0439647598550091e-50
3.975821558248423e-23
2.741267029728437e-78
7.198082940390491e-106
4.280845047327843e-69
3.975821558248423e-23
7.755927282256581e-57
2.9537135607967343e-29
3.975821558248423e-23
1.124074282857378e-96
3.975821558248423e-23
1.8914290714091943e-38
2.9537135607967343e-29
3.42685144564196e-26
5.3549356554603165e-17
1.0439647598550091e-50
3.6898053220973413e-72
6.204271457788388e-109
4.6130626872419715e-20
5.3549356554603165e-17
3.975821558248423e-23
7.755927282256581e-57
0.00021355610277377517
2.9537135607967343e-29
2.362790889124965e-81
7.755927282256581e-57
1.8914290714091943e-38
1.2111889332108396e-47
6.685096388091307e-60
3.42685144564196e-26
8.998285816015186e-54
4.966558590363448e-66
3.42685144564196e-26
1.755388210784887e-87
2.9537135607967343e-29
1.124074282857378e-96
1.5130285471425918e-90
6.685096388091307e-60
8.998285816015186e-54
1.2111889332108396e-47
8.998285816015186e-54
2.362790889124965e-81
4.6130626872419715e-20
3.975821558248423e-23
1.4051993787285787e-44
2.9537135607967343e-29
3.975821558248423e-23
4.280845047327843e-69
1.4051993787285787e-44
2.036569486003339e-84
1.0439647598550091e-50
2.741267029728437e-78
2.036569486003339e-84
2.741267029728437e-78
2.9537135607967343e-29
2.9537135607967343e-29
3.1803681666722106e-75
1.4051993787285787e-44
2.1944016341686676e-35
2.9537135607967343e-29
6.685096388091307e-60
4.280845047327843e-69
5.3549356554603165e-17
5.3549356554603165e-17
2.9537135607967343e-29
6.235109128196901e-14
8.998285816015186e-54
3.975821558248423e-23
3.42685144564196e-26
1.4051993787285787e-44
9.888866940702522e-08
7.755927282256581e-57
1.304130545256896e-93
1.0439647598550091e-50
5.3549356554603165e-17
9.888866940702522e-08
2.5459049929848763e-32
1.6302867703825892e-41
2.5459049929848763e-32
6.235109128196901e-14
5.3549356554603165e-17
7.404437851135338e-11
1.8914290714091943e-38
3.975821558248423e-23
3.42685144564196e-26
3.6898053220973413e-72
1.6291320784711136e-136
7.755927282256581e-57
6.235109128196901e-14
4.6130626872419715e-20
3.975821558248423e-23
3.42685144564196e-26
2.741267029728437e-78
1.6302867703825892e-41
1.8914290714091943e-38
1.124074282857378e-96
7.755927282256581e-57
2.9537135607967343e-29
4.280845047327843e-69
3.97294566906523e-118
4.6130626872419715e-20
1.6302867703825892e-41
9.888866940702522e-08
1.6302867703825892e-41
7.755927282256581e-57
6.235109128196901e-14
1.8914290714091943e-38
4.966558590363448e-66
1.4051993787285787e-44
1.8914290714091943e-38
1.0439647598550091e-50
3.42685144564196e-26
4.6130626872419715e-20
1.6302867703825892e-41
5.3549356554603165e-17
1.2111889332108396e-47
4.6130626872419715e-20
2.036569486003339e-84
6.685096388091307e-60
8.998285816015186e-54
1.6302867703825892e-41
8.998285816015186e-54
3.42685144564196e-26
2.036569486003339e-84
1.2111889332108396e-47
7.404437851135338e-11
7.755927282256581e-57
3.42685144564196e-26
3.42685144564196e-26
4.280845047327843e-69
4.6130626872419715e-20
9.688776924801092e-100
3.42685144564196e-26
2.036569486003339e-84
2.5459049929848763e-32
3.975821558248423e-23
2.1944016341686676e-35
6.685096388091307e-60
2.5459049929848763e-32
4.6130626872419715e-20
1.6302867703825892e-41
6.685096388091307e-60
1.2111889332108396e-47
3.975821558248423e-23
1.8914290714091943e-38
1.304130545256896e-93
7.404437851135338e-11
8.998285816015186e-54
3.1803681666722106e-75
2.5459049929848763e-32
8.998285816015186e-54
6.685096388091307e-60
4.6130626872419715e-20
2.5459049929848763e-32
5.3549356554603165e-17
7.198082940390491e-106
1.8914290714091943e-38
7.404437851135338e-11
2.5459049929848763e-32
7.755927282256581e-57
1.2111889332108396e-47
5.3549356554603165e-17
3.975821558248423e-23
9.888866940702522e-08
2.1944016341686676e-35
5.3549356554603165e-17
2.9537135607967343e-29
7.404437851135338e-11
1.2111889332108396e-47
1.2111889332108396e-47
6.685096388091307e-60
8.351084953205769e-103
4.6130626872419715e-20
2.5459049929848763e-32
7.755927282256581e-57
1.2111889332108396e-47
4.6130626872419715e-20
1.4051993787285787e-44
6.235109128196901e-14
3.975821558248423e-23
6.235109128196901e-14
2.036569486003339e-84
8.998285816015186e-54
2.9537135607967343e-29
3.975821558248423e-23
9.888866940702522e-08
5.3549356554603165e-17
2.5459049929848763e-32
4.6130626872419715e-20
3.42685144564196e-26
2.5459049929848763e-32
4.6130626872419715e-20
1.304130545256896e-93
4.280845047327843e-69
8.998285816015186e-54
5.3549356554603165e-17
1.6302867703825892e-41
3.42685144564196e-26
1.0439647598550091e-50
6.685096388091307e-60
4.280845047327843e-69
5.3549356554603165e-17
5.3549356554603165e-17
1.6302867703825892e-41
5.762110975474395e-63
1.2103310781847287e-142
1.2111889332108396e-47
2.036569486003339e-84
7.755927282256581e-57
4.6130626872419715e-20
8.998285816015186e-54
1.0439647598550091e-50
1.0439647598550091e-50
4.6130626872419715e-20
8.998285816015186e-54
1.0439647598550091e-50
8.351084953205769e-103
2.5459049929848763e-32
4.6130626872419715e-20
5.762110975474395e-63
2.5459049929848763e-32
4.6130626872419715e-20
1.6302867703825892e-41
5.3549356554603165e-17
4.6130626872419715e-20
8.998285816015186e-54
3.975821558248423e-23
4.6130626872419715e-20
3.42685144564196e-26
3.6898053220973413e-72
5.3549356554603165e-17
1.6302867703825892e-41
5.3549356554603165e-17
4.966558590363448e-66
2.9537135607967343e-29
9.888866940702522e-08
7.404437851135338e-11
5.762110975474395e-63
2.362790889124965e-81
3.6898053220973413e-72
7.198082940390491e-106
2.1944016341686676e-35
5.3549356554603165e-17
2.1944016341686676e-35
2.9537135607967343e-29
6.235109128196901e-14
7.404437851135338e-11
2.036569486003339e-84
1.755388210784887e-87
1.4051993787285787e-44
4.6130626872419715e-20
3.42685144564196e-26
1.5130285471425918e-90
1.5130285471425918e-90
8.998285816015186e-54
4.966558590363448e-66
4.6130626872419715e-20
3.1803681666722106e-75
3.42685144564196e-26
1.6302867703825892e-41

,Class,Email,Count,Classification
3634,ham,ltgt w jetton ave if you forgot,8,spam
3635,ham,ok im coming home now,5,spam
3636,ham,can not use foreign stamps in this country,8,spam
3637,ham,sorry its a lot of friendofafriend stuff im ju...,21,spam
3638,spam,cmon babe make me horny turn me on txt me your...,30,spam
3639,ham,wylie update my weed dealer carlos went to fre...,15,spam
3640,ham,are you happy baby are you alright did you t...,35,spam
3641,ham,c movie is juz last minute decision mah juz wa...,18,spam
3642,ham,how are you enjoying this semester take care b...,9,spam
3643,spam,important information 4 orange user 0796xxxxxx...,22,spam

In [109]:
df_test[df_test['Classification'] == 'ham']

     Class                   Email  Count Classification
3720   ham                     gwr      1            ham
3883   ham  erutupalam thandiyachu      2            ham
4026   ham                  havent      1            ham
4076   ham                 anytime      1            ham
4104   ham   keng rocking in ashes      4            ham
4286   ham       kkcongratulation       2            ham
4574   ham                      er      1            ham
4706   ham              east coast      2            ham